# Set the base image
FROM node:16.16.0-alpine AS build

# Set the environment variables for the database connection
ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}
ARG DB_DIALECT
ENV DB_DIALECT=${DB_DIALECT}
ARG DB_HOST
ENV DB_HOST=${DB_HOST}
ARG DB_PORT
ENV DB_PORT=${DB_PORT}
ARG DB_USER
ENV DB_USER=${DB_USER}
ARG DB_PASS
ENV DB_PASS=${DB_PASS}
ARG DB_NAME
ENV DB_NAME=${DB_NAME}

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application files to the container
COPY . .

# Expose the port that the application will run on
EXPOSE 3000


# Start the application
CMD ["npm", "run", "start:prod"]