version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        JWT_SECRET: secret
        DB_DIALECT: postgres
        DB_HOST: postgres
        DB_PORT: 5432
        DB_USER: postgres
        DB_PASS: postgres
        DB_NAME: postgres
    ports:
      - '3000:3000'
    depends_on:
      - postgres

volumes:
  postgres_data:
