export { SignUp } from './SignUp';
export { SignIn } from './SignIn';
export { MyProfile } from './Profile';
export { Home } from './Home';
export { Password } from './Password';
export { ProfileEdit } from './ProfileEdit';
export { Devices } from './Devices';
export { Details } from './Details';
export { NotFound } from './404';
